### ISSUE TITLE
No module named 'pythia.utils.graph_construction'

### ISSUE THREAD

**Issue by soonchangAI** [SelinaFelton/SBD-Trans#1]
## ❓ Questions and Help
Hi, first of all, thanks for sharing the code.
I ran the code for training and faced an error
Command:
`python tools/run.py --tasks vqa --datasets m4c_textvqa --model m4c \
--config configs/vqa/textvqa/sma.yml \
--save_dir save/m4c \
training_parameters.data_parallel True`

Error:
`    from pythia.utils.graph_construction import gen_intra_edge_feature
ModuleNotFoundError: No module named 'pythia.utils.graph_construction'
`

**Comment by HowardLi1984** [comment]
in Pythia.py, you import four functions and none of them is released
`from pythia.utils.graph_construction import gen_intra_edge_feature
from pythia.utils.graph_construction import gen_extra_edge_feature
from pythia.utils.graph_construction import find_k_nearest_node
from pythia.utils.graph_construction import hetero_find_k_nearest_node`
