### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by leonodelee** [SelinaFelton/SBD-Trans#2]
## ❓ Questions and Help
I wonder if I can get GT OCR Annotations for Textcaps? And the imdb files (with SBD-Trans OCR) for Textcaps dataset? Different from TextVQA, it should include the key "caption" instead of "answer ".

**Comment by ChenyuGAO-CS** [comment]
We have not labeled GT OCR for Textcaps. As SMA was mainly designed for the TextVQA task, we have not prepared other Textcaps-specific data files.
